### ISSUE TITLE
The 'encrypted_session_expires' directive in the example.

### ISSUE THREAD

**Issue by vkvj** [openresty/encrypted-session-nginx-module#18]
Hi,

Could you please change your example. Specifically, increase the value for the 'encrypted_session_expires' directive:

`encrypted_session_expires 2; # in sec`

For example to 30 seconds:
`encrypted_session_expires 30; # in sec`

We have a feedback from the real customer who had a problem using your example.
The value equal to 2 seconds is too short for testing by hand.

And I afraid we will get more such issues in the future.

Thank you.

**Comment by Koxx3** [comment]
+1
it took me 1 day to figure it out ...
yes ... i know ...
but the example should work without having to question why not.

**Comment by agentzh** [comment]
Done. Next time please just create a pull request ;)
